apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: ClusterIP #internal-access-only
  selector:
    app: app-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000