name: CD - Deploy to EKS

on:
  workflow_dispatch:   # manual trigger from Actions tab
  push:
    branches:
      - master         # auto-deploy when pushing to master (change if needed)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo to access YAML files
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Configure AWS CLI
      - name: Configure AWS CLI
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "[default]" > ~/.aws/config
          echo "region=${{ secrets.AWS_REGION }}" >> ~/.aws/config

      # 3. Update kubeconfig so kubectl can talk to your EKS cluster
      - name: Update kubeconfig for EKS
        run: aws eks update-kubeconfig --name test_cluster --region ${{ secrets.AWS_REGION }}

      # 4. Deploy manifests
      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/web-deployment.yaml
          kubectl apply -f k8s/web-service.yaml

      # 5. Restart deployment (ensures pods pull the latest :latest image)
      - name: Restart deployment
        run: |
          kubectl rollout restart deployment web-deployment
          kubectl rollout status deployment web-deployment
