name: CI - Build and Push to ECR

on:
  push:
    branches:
      - master   # change to 'main' if that's your default branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Debug secrets
      - name: Debug Secrets
        run: |
          echo "AWS_ACCESS_KEY_ID = ${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY length =" $(echo -n "${{ secrets.AWS_SECRET_ACCESS_KEY }}" | wc -c)
          echo "ECR_REPOSITORY = ${{ secrets.ECR_REPOSITORY }}"

      # 3. Configure AWS CLI manually (credentials only)
      - name: Configure AWS CLI manually
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

      # 4. Test AWS CLI authentication (inline region)
      - name: Test AWS CLI
        run: aws sts get-caller-identity --region us-east-1

      # 5. Run Unit Tests (skip if no package.json)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies & run tests
        run: |
          if [ -f package.json ]; then
            npm install
            npm test
          else
            echo "No package.json found, skipping npm install/test"
          fi

      # 6. Authenticate Docker to Amazon ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 \
          | docker login --username AWS --password-stdin \
            $(aws sts get-caller-identity --query Account --output text --region us-east-1).dkr.ecr.us-east-1.amazonaws.com

      # 7. Build & Push Docker Image
      - name: Build, Tag, and Push
        run: |
          IMAGE_TAG=${GITHUB_SHA}
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text --region us-east-1)
          ECR_REGISTRY=$AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY=${{ secrets.ECR_REPOSITORY }}

          echo "Building image $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
